### ISSUE TITLE
Define extras_require for individual formats

### ISSUE THREAD

**Issue by ziima** [welbornprod/easysettings#6]
Add `extras_require` to `setup.py` to define libraries required for JSON/YAML/TOML settings.

**Comment by cjwelborn** [comment]
I can do that. JSON should be in the standard library already (no pypi install needed). I use `JSONSettings` (actually `load_json_settings()` because it's less code) in almost all of my projects. I added YAML and TOML as "optional requirements" because I wasn't sure if anyone used them with `EasySettings`. It was really easy to add wrappers around those because of their similar interface/api, and I was experimenting with what I liked the best for my own projects. Since you asked though, it's a very simple change to make and I'll get to it when I get home.

Thanks for filing the issue.

**Comment by cjwelborn** [comment]
There are `'toml'` and `'yaml'` extras now. This works:
```bash
pip install 'easysettings[yaml,toml]' --user
```

Or just:
```bash
pip install easysettings[all]
```

I accidentally used 'install_requires' by pure instinct (3.3.0), fixed that (3.3.1), and then realized I could make the 'all' requirement in case someone wants to try everything (3.3.2). One minor release, and two micro releases in about fifteen minutes. That's what I get for rushing.

Anyway, thanks again for filing the issue. You should be good now.

**Comment by cjwelborn** [comment]
I'll update the docs/readme to include this.

**Comment by ziima** [comment]
:+1:
